name: Build and Push Both Services

on:
    push:
        branches: ["main"]
        tags: ["v*"]

jobs:
    build-frontend:
        name: Build and Push Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Build Frontend
              run: |
                  rm -rf node_modules package-lock.json
                  npm install --force
                  npm run build

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push Frontend Image
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/alax_tax_frontend:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/alax_tax_frontend:${{ github.sha }}
